version: '3.8'

services:
  sensoria_db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - sensoria_db:/var/lib/postgresql/data
    networks:
      - sensoria_network

volumes:
  sensoria_db:

networks:
  sensoria_network:
    driver: bridge
